<?php

$Root = dirname(__FILE__);

$Render = function() use($Root) {
	$RenderCmd = NULL;
	$RenderOut = NULL;
	$RenderErr = NULL;

	if(isset($_GET['compile'])) {
		switch($_GET['compile']) {
			case '1':
				$RenderCmd = sprintf('php %s/bin/nsen render',$Root);
			break;
			case '2':
				$RenderCmd = sprintf('php %s\bin\nsen run src',$Root);
			break;
		}
	}

	$RenderCmd = sprintf('php %s/bin/nsen render',$Root);

	if(!$RenderCmd)
	return TRUE;

	exec($RenderCmd,$RenderOut,$RenderErr);

	if($RenderErr) {
		echo '<pre>';
		join('<br />',$RenderOut);
		echo '</pre>';

		return FALSE;
	}

	return TRUE;
};

$RequestURI = (function(){
	$URI = trim($_SERVER['REQUEST_URI'],'/');

	if(str_contains($URI,'?'))
	$URI = explode('?',$URI)[0];

	if($URI === '')
	$URI = 'index.html';

	return $URI;
})();

$RequestFile = join(
	DIRECTORY_SEPARATOR,
	[$Root, 'docs', $RequestURI]
);

$Rendered = FALSE;

////////

// if a file does not exist at the location in this particular project that
// most likely means it just hasn't been generated yet.

if(!file_exists($RequestFile))
if(!($Rendered = $Render()))
return TRUE;

// if we asked for an html file that exists its possible it is out of date
// so trigger a render if we haven't already.

if(file_exists($RequestFile))
if(str_ends_with($RequestURI,'.html')) {
	if(!$Rendered && !$Render())
	return TRUE;

	// if the file did not exist before the first triggered render above
	// it seems that php-cli's webserver has already decided that the file
	// does not exist, so it shoots a 404 instead of serving the file that
	// was generated by this process. so if it is an html file we generated
	// we will just pass it on through.

	echo file_get_contents($RequestFile);
	return TRUE;
}

return FALSE;
