<?php

use Nether\Sensei\Util;

$Foreign = ($Codebase->Classes->HasKey($Class->Extends) === FALSE);
$Trail = $Engine->GetNamespaceLinks(Util::GetNamespaceName($Class->Extends));
$Main = array_pop($Trail);

?>

<div class="mb-6">
	<hr class="m-0" />
	<div class="font-weight-bold text-uppercase mb-4">Extends</div>

	<div class="jumbotron jumbotron-dark p-4">
		<?php if($Foreign): ?>
		<div class="mb-1">
			<span class="Tag">foreign</span>
		</div>
		<h3 class="m-0 p-0 lh-1"><?php echo Util::GetNamespaceName($Class->Extends) ?></h3>
		<?php else: ?>
		<?php if(count($Trail)): ?>
		<div class="mb-2">
			<?php foreach($Trail as $Link): ?>
			<span class="text-muted">&gt;</span> <?php echo $Link ?>
			<?php endforeach; ?>
		</div>
		<?php endif; ?>
		<h3 class="LinkLight m-0 p-0 lh-1"><?php echo $Main ?></h3>
		<?php endif; ?>
	</div>
</div>
