<?php

use Nether\Sensei\Util;

$IsForeign = function($Input) use($Codebase) {
	return $Codebase->Interfaces->HasKey($Input) === FALSE;
};

?>

<div class="mb-6">
	<hr class="m-0" />
	<div class="font-weight-bold text-uppercase mb-4">Interfaces</div>

	<?php foreach($Class->Interfaces as $Iface): ?>
	<div class="mb-4">
		<div class="jumbotron jumbotron-dark p-4">
			<?php if($IsForeign($Iface)): ?>
			<div class="mb-1">
				<span class="Tag">foreign</span>
			</div>
			<?php endif; ?>

			<h3 class="FontCode m-0 p-0 lh-1">
				<?php echo Util::GetNamespaceName($Iface) ?>
			</h3>
		</div>
	</div>
	<?php endforeach; ?>
</div>
