<?php

use Nether\Sensei\Util;

/**
 * @var Nether\Sensei\ThemeEngine $Engine
 * @var Nether\Sensei\Codebase $Codebase
 * @var Nether\Sensei\Inspectors\ClassInspector $Class
 */

$Trail = $Engine->GetNamespaceLinks(Util::GetNamespaceName($Class->Name));
$Main = array_pop($Trail);

?>

<div class="mb-6">
	<div class="jumbotron jumbotron-dark p-4">
		<div class="mb-1">
			<?php if($Class->Abstract): ?>
			<span class="Tag Primary">abstract</span>
			<?php endif; ?>
			<?php if($Class->Final): ?>
			<span class="Tag Primary">final</span>
			<?php endif; ?>
			<?php if($Class->Attribute): ?>
			<span class="Tag Primary">attribute</span>
			<?php else: ?>
			<span class="Tag Primary">class</span>
			<?php endif; ?>
		</div>
		<h2 class="m-0 mb-2 p-0 lh-1"><?php echo $Class->GetBaseName() ?></h2>
		<?php if(count($Trail)): ?>
		<div class="mb-0">
			<?php foreach($Trail as $Link): ?>
			<span class="text-muted">&gt;</span> <?php echo $Link ?>
			<?php endforeach; ?>
		</div>
		<?php endif; ?>

		<?php if($Class->Info): ?>
		<blockquote class="mt-3 mb-0 opacity-50">
			<?php echo htmlentities($Class->Info->Text) ?>
		</blockquote>
		<?php endif; ?>
	</div>
</div>
