<?php

use Nether\Sensei\Util;

$Foreign = ($Codebase->Classes->HasKey($Class->Extends) === FALSE);
$Trail = $Engine->GetNamespaceLinks(Util::GetNamespaceName($Class->Extends));
$Main = array_pop($Trail);

?>

<div class="mb-6">
	<hr class="m-0" />
	<div class="font-weight-bold text-uppercase mb-4">Extends</div>

	<div class="jumbotron jumbotron-dark p-4">
		<div class="mb-1">
			<?php if($Foreign && Util::IsBuiltInClass($Class->Extends)): ?>
			<span class="Tag Secondary">php</span>
			<?php elseif($Foreign): ?>
			<span class="Tag">foreign</span>
			<?php endif; ?>
			<span class="Tag Primary">class</span>
		</div>
		<h3 class="LinkLight m-0 p-0 lh-1">
			<?php if($Foreign && Util::IsBuiltInClass($Class->Extends)): ?>
			<a href="<?php echo Util::GetClassManualURL($Class->Extends) ?>" target="_blank"><?php echo strip_tags($Main) ?></a>
			<?php elseif($Foreign): ?>
			<?php echo $Main ?>
			<?php endif; ?>
		</h3>
		<?php if(count($Trail)): ?>
		<div class="mb-2">
			<?php foreach($Trail as $Link): ?>
			<span class="text-muted">&gt;</span> <?php echo $Link ?>
			<?php endforeach; ?>
		</div>
		<?php endif; ?>

	</div>
</div>
