<?php

use Nether\Sensei\Util;

$IsForeign = function($Input) use($Codebase) {
	return $Codebase->Interfaces->HasKey($Input) === FALSE;
};

?>

<div class="mb-6">
	<div class="font-weight-bold text-uppercase">Implements</div>
	<hr class="mt-1" />

	<?php foreach($Class->Interfaces as $Iface): ?>
	<div class="mb-6">
		<?php if($IsForeign($Iface)): ?>
		<div class="mb-1">
			<span class="Tag">foreign</span>
		</div>
		<?php endif; ?>

		<h3 class="FontCode">
			<?php echo Util::GetNamespaceName($Iface) ?>
		</h3>
	</div>
	<?php endforeach; ?>
</div>
