<?php

$GetPrefix = function(Nether\Sensei\Inspectors\PropertyInspector $Input) {

	if($Input->Static)
	return 'static::';

	return '$this->';
};

?>
<div class="mb-6">
	<div class="font-weight-bold text-uppercase">Properties</div>
	<hr class="mt-1" />

	<?php foreach($Class->Properties as $Prop): ?>
	<div class="mb-6">
		<div class="mb-1">
			<?php if($Prop->Static): ?>
			<span class="Tag Primary">static</span>
			<?php endif; ?>
			<span class="Tag Primary"><?php echo $Prop->GetAccessWord() ?></span>
			<span class="Tag Type"><?php echo $Prop->Type, PHP_EOL ?></span>
		</div>

		<h3 class="FontCode">
			<span class="text-muted"><?php echo $GetPrefix($Prop) ?></span><?php echo $Prop->GetName() ?>
		</h3>
	</div>
	<?php endforeach; ?>

</div>