<?php

use Nether\Sensei\Util;

$IsForeign = function($Input) use($Codebase) {
	return $Codebase->Interfaces->HasKey($Input) === FALSE;
};

?>

<div class="mb-6">
	<hr class="m-0" />
	<div class="font-weight-bold text-uppercase mb-4">Interfaces</div>

	<?php foreach($Class->Interfaces as $IFace): ?>
	<div class="mb-4">
		<div class="jumbotron jumbotron-dark p-4">
			<?php if($IsForeign($IFace)): ?>
			<div class="mb-1">
				<?php if(Util::IsBuiltInInterface($IFace)): ?>
				<span class="Tag Secondary">php</span>
				<?php else: ?>
				<span class="Tag">foreign</span>
				<?php endif; ?>
				<span class="Tag Primary">interface</span>
			</div>
			<?php endif; ?>

			<h3 class="LinkLight m-0 p-0 lh-1">
				<?php if(Util::IsBuiltInInterface($IFace)): ?>
				<a href="<?php echo Util::GetClassManualURL($IFace) ?>" target="_blank"><?php echo $IFace ?></a>
				<?php else: ?>
				<?php echo Util::GetNamespaceName($IFace) ?>
				<?php endif; ?>
			</h3>
		</div>
	</div>
	<?php endforeach; ?>
</div>
