<?php

use Nether\Sensei\Util;

$Foreign = ($Codebase->Classes->HasKey($Class->Extends) === FALSE);
$Trail = $Engine->GetNamespaceLinks(Util::GetNamespaceName($Class->Extends));
$Main = array_pop($Trail);

?>

<div class="mb-6">
	<div class="font-weight-bold text-uppercase">Extends</div>
	<hr class="mt-1" />

	<?php if($Foreign): ?>
	<div class="mb-1">
		<span class="Tag">foreign</span>
	</div>
	<h2><?php echo Util::GetNamespaceName($Class->Extends) ?></h2>
	<?php else: ?>
	<?php if(count($Trail)): ?>
	<div class="mb-2">
		<?php foreach($Trail as $Link): ?>
		<span class="text-muted">&gt;</span> <?php echo $Link ?>
		<?php endforeach; ?>
	</div>
	<?php endif; ?>
	<h2><?php echo $Main ?></h2>
	<?php endif; ?>
</div>
