<?php

$GetPrefix = function(Nether\Sensei\Inspectors\PropertyInspector $Input) {

	if($Input->Static)
	return 'static::';

	return '$this->';
};

?>
<div class="mb-6">
	<hr class="m-0" />
	<div class="font-weight-bold text-uppercase mb-4">Properties</div>

	<div class="jumbotron jumbotron-dark p-4 HideTheLastHr">
		<?php foreach($Class->Properties as $Prop): ?>
		<div>
			<div class="mb-1">
				<?php if($Prop->Static): ?>
				<span class="Tag Class">static</span>
				<?php endif; ?>
				<span class="Tag Primary"><?php echo $Prop->GetAccessWord() ?></span>
				<span class="Tag Type"><?php echo $Prop->Type, PHP_EOL ?></span>
			</div>

			<h3 class="FontCode m-0 p-0 lh-1">
				<span class="opacity-25"><?php echo $GetPrefix($Prop) ?></span><?php echo $Prop->GetName() ?>
			</h3>
		</div>
		<hr class="mt-5 mb-5 opacity-25" />
		<?php endforeach; ?>
	</div>

</div>