<?php

use Nether\Sensei\Util;

/**
 * @var Nether\Sensei\ThemeEngine $Engine
 * @var Nether\Sensei\Codebase $Codebase
 * @var Nether\Sensei\Inspectors\NamespaceInspector $Namespace
 */

$IsForeign = function($Input) use($Codebase) {
	return $Codebase->Classes->HasKey($Input) === FALSE;
};

?>

<div class="mb-6">
	<hr class="m-0" />
	<div class="font-weight-bold text-uppercase mb-4">Classes</div>

	<div class="jumbotron jumbotron-dark p-4">
		<?php foreach($Namespace->Classes as $CKey => $Class): ?>
		<div class="<?php echo $Codebase->Classes->IsLastKey($CKey) ? 'mb-0' : 'mb-4' ?>">
			<div class="FontCode m-0 p-0 lh-1">
				<?php foreach($Engine->GetNamespaceLinks(Util::GetNamespaceName($Class->Name)) as $Link): ?>
				<span class="text-muted">&gt;</span> <?php echo $Link ?>
				<?php endforeach; ?>
			</div>
		</div>
		<?php endforeach; ?>
	</div>
</div>
