<?php

use Nether\Sensei\Util;
use Nether\Sensei\Inspectors\MethodInspector;
use Nether\Sensei\Inspectors\PropertyInspector;

/**
 * @var Nether\Sensei\ThemeEngine $Engine
 * @var Nether\Sensei\Codebase $Codebase
 * @var Nether\Sensei\Inspectors\ClassInspector $Class
 */

$Engine->Set('PageTitle',"{$Class->GetClassName()} (Class)");

?>

<div class="container">

	<?php

	echo $Engine->Element(
		'class-header',
		Class: $Class,
		Codebase: $Codebase
	);

	if($Class->Extends)
	echo $Engine->Element(
		'class-extends',
		Class: $Class,
		Codebase: $Codebase
	);

	if($Class->Interfaces->Count())
	echo $Engine->Element(
		'class-interfaces',
		Class: $Class,
		Codebase: $Codebase
	);

	if($Class->Constants->Count())
	echo $Engine->Element(
		'class-constants',
		Class: $Class,
		Codebase: $Codebase
	);

	if($Class->Properties->Count())
	echo $Engine->Element(
		'class-properties',
		Class: $Class,
		Codebase: $Codebase
	);

	if($Class->Methods->Count())
	echo $Engine->Element(
		'class-methods',
		Class: $Class,
		Codebase: $Codebase
	);

	?>


</div>
