<?php

use Nether\Sensei\Util;

/**
 * @var Nether\Sensei\ThemeEngine $Engine
 * @var Nether\Sensei\Codebase $Codebase
 * @var Nether\Sensei\Inspectors\NamespaceInspector $Namespace
 */

$Engine->Set('PageTitle',"{$Namespace->Name} (Namespace)");

?>

<div class="container">

	<?php

	echo $Engine->Element(
		'namespace-header',
		Namespace: $Namespace,
		Codebase: $Codebase
	);

	if($Namespace->Namespaces->Count())
	echo $Engine->Element(
		'namespace-namespaces',
		Namespace: $Namespace,
		Codebase: $Codebase
	);

	if($Namespace->Classes->Count())
	echo $Engine->Element(
		'namespace-classes',
		Namespace: $Namespace,
		Codebase: $Codebase
	);

	?>

</div>
