<?php

use Nether\Sensei\Util;

/**
 * @var Nether\Sensei\ThemeEngine $Engine
 * @var Nether\Sensei\Codebase $Codebase
 */

?>
<!doctype html>
<html>
<head>
	<title><?php echo $PageTitle ?></title>
	<link rel="stylesheet" type="text/css" href="<?php echo $Engine->GetAssetURL('share/bootstrap.min.css') ?>" />
	<link rel="stylesheet" type="text/css" href="<?php echo $Engine->GetAssetURL('share/theme.css') ?>" />
</head>
<body>

<header class="mb-6 pt-6">
	<div class="container">
		<div class="p-4 rounded" style="background:#000a;">
			<h1 class="LinkLight m-0 p-0 lh-1 text-center">
				<a href="<?php echo $Engine->GetAssetURL('/') ?>">---</a>
			</h1>
		</div>
	</div>
</header>

<?php echo $PageOutput, "\n" ?>

</body>
</html>